/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iot.conversormedidas;

import javax.swing.JOptionPane;

/**
 *
 * @author Desktop
 */
public class conversorTela extends javax.swing.JFrame {

    /**
     * Creates new form conversorTela
     */
    public conversorTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelValorConvertido1 = new javax.swing.JLabel();
        jLabelValorEmCentimetros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmKmConvertButton = new javax.swing.JButton();
        cmMConvertbutton = new javax.swing.JButton();
        cmMmConvertButton = new javax.swing.JButton();
        alterarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 250));
        setMinimumSize(new java.awt.Dimension(430, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelValorConvertido1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelValorConvertido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 89, 104, 28));

        jLabelValorEmCentimetros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabelValorEmCentimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelValorEmCentimetrosActionPerformed(evt);
            }
        });
        getContentPane().add(jLabelValorEmCentimetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 37, 104, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Insira um valor em cm:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 36, -1, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Valor convertido em ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 89, -1, 28));

        cmKmConvertButton.setText("Cm para km");
        cmKmConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmKmConvertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cmKmConvertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 150, -1, -1));

        cmMConvertbutton.setText("Cm para m");
        cmMConvertbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmMConvertbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(cmMConvertbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 150, -1, -1));

        cmMmConvertButton.setText("Cm para mm");
        cmMmConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmMmConvertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cmMmConvertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 150, -1, -1));
        getContentPane().add(alterarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 89, 63, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelValorEmCentimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelValorEmCentimetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelValorEmCentimetrosActionPerformed

    private void cmKmConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmKmConvertButtonActionPerformed
        // TODO add your handling code here:
        Double  numero;
        numero = Double.parseDouble(jLabelValorEmCentimetros.getText());
        Double resultado = numero/1000;
        alterarLabel.setText("quilometro");
        if(numero >=0)
        jLabelValorConvertido1.setText(""+resultado);
        else
        JOptionPane.showMessageDialog (null, "ERRO valor menor que 0");
    }//GEN-LAST:event_cmKmConvertButtonActionPerformed

    private void cmMConvertbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmMConvertbuttonActionPerformed
        // TODO add your handling code here:
        Double  numero;
        numero = Double.parseDouble(jLabelValorEmCentimetros.getText());
        Double resultado = numero/100;
        alterarLabel.setText("metro");
        if(numero >=0)
        jLabelValorConvertido1.setText(""+resultado);
        else
        JOptionPane.showMessageDialog (null, "ERRO valor menor que 0");
    }//GEN-LAST:event_cmMConvertbuttonActionPerformed

    private void cmMmConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmMmConvertButtonActionPerformed
        // TODO add your handling code here:
        Double  numero;
        alterarLabel.setText("milimetro");
        numero = Double.parseDouble(jLabelValorEmCentimetros.getText());
        Double resultado = numero/10;
        if(numero >=0)
        jLabelValorConvertido1.setText(""+resultado);
        else
        JOptionPane.showMessageDialog (null, "ERRO valor menor que 0");
    }//GEN-LAST:event_cmMmConvertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversorTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alterarLabel;
    private javax.swing.JButton cmKmConvertButton;
    private javax.swing.JButton cmMConvertbutton;
    private javax.swing.JButton cmMmConvertButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelValorConvertido1;
    private javax.swing.JTextField jLabelValorEmCentimetros;
    // End of variables declaration//GEN-END:variables
}
